title: Siavash Monfared # your name (or website title) here
logo: "/images/FullSizeRender.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Postdoctoral Scholar
  <br>
  California Institute of Technology
  <br><br>
  <a href = "mailto: monfared@caltech.edu">Contact</a>
  <br>
  <a href="https://scholar.google.com/citations?user=E9GMpVEAAAAJ&hl=en">Google Scholar page</a> 
  
  <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
  <a href"https://www.theguardian.com/us"><span class="iconify" data-icon="logos-github-icon" data-inline="false"></span></a>
  <span class="iconify" data-icon="simple-icons:googlescholar" data-inline="false"></span>
  <span class="iconify" data-icon="simple-icons:orcid" data-inline="false" data-width="2em" data-height="2em"></span>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
